/* AeroBench-SITL — STM32G071RB Flight Computer
 *
 * main.c: peripheral init, global IPC objects, task creation.
 *
 * CubeMX generates MX_*_Init() functions and HAL handles.
 * This file owns the application layer above that.
 *
 * FreeRTOS objects:
 *   g_sensor_queue   — sensor_data_t frames from QEMU → FSM task
 *   g_state_mutex    — protects fsm_ctx_t + s_last_sensors
 *   g_fault_flags    — EventGroup of FAULT_FLAG_* bits
 */

#include "main.h"
#include "cmsis_os.h"
#include "protocol.h"
#include "sensor_data.h"
#include "blackbox.h"
#include "health_monitor.h"
#include <string.h>

/* ------------------------------------------------------------------ */
/*  HAL handles (generated by CubeMX — do not rename)                 */
/* ------------------------------------------------------------------ */

UART_HandleTypeDef huart2;
IWDG_HandleTypeDef hiwdg;
CRC_HandleTypeDef  hcrc;

/* ------------------------------------------------------------------ */
/*  Global FreeRTOS IPC objects                                        */
/* ------------------------------------------------------------------ */

osMessageQueueId_t g_sensor_queue;
osMutexId_t        g_state_mutex;
osEventFlagsId_t   g_fault_flags;

/* ------------------------------------------------------------------ */
/*  Global black-box buffer (declared extern in all task files)        */
/* ------------------------------------------------------------------ */

blackbox_t g_blackbox;

/* ------------------------------------------------------------------ */
/*  Task handles (filled after osThreadNew, passed to health monitor)  */
/* ------------------------------------------------------------------ */

static osThreadId_t h_sensor_task;
static osThreadId_t h_fsm_task;
static osThreadId_t h_telemetry_task;
static osThreadId_t h_health_task;

/* ------------------------------------------------------------------ */
/*  Task attributes                                                     */
/* ------------------------------------------------------------------ */

static const osThreadAttr_t sensor_attr = {
    .name       = "SensorTask",
    .stack_size = 512,
    .priority   = osPriorityAboveNormal,
};

static const osThreadAttr_t fsm_attr = {
    .name       = "FSMTask",
    .stack_size = 512,
    .priority   = osPriorityAboveNormal,
};

static const osThreadAttr_t telemetry_attr = {
    .name       = "TelemetryTask",
    .stack_size = 512,
    .priority   = osPriorityNormal,
};

static const osThreadAttr_t health_attr = {
    .name       = "HealthTask",
    .stack_size = 256,
    .priority   = osPriorityNormal,
};

/* ------------------------------------------------------------------ */
/*  Task entry point prototypes (defined in task_*.c)                  */
/* ------------------------------------------------------------------ */

void task_sensor(void *argument);
void task_fsm(void *argument);
void task_telemetry(void *argument);
void task_health(void *argument);

/* ------------------------------------------------------------------ */
/*  Peripheral init — CubeMX generates the bodies; stubs here          */
/* ------------------------------------------------------------------ */

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK)
        Error_Handler();
}

static void MX_IWDG_Init(void)
{
    /* ~1 second timeout at 32 kHz LSI / 256 prescaler */
    hiwdg.Instance       = IWDG;
    hiwdg.Init.Prescaler = IWDG_PRESCALER_256;
    hiwdg.Init.Reload    = 125;   /* 125 × (256/32000) ≈ 1.0 s */
    hiwdg.Init.Window    = IWDG_WINDOW_DISABLE;
    if (HAL_IWDG_Init(&hiwdg) != HAL_OK)
        Error_Handler();
}

static void MX_CRC_Init(void)
{
    hcrc.Instance = CRC;
    if (HAL_CRC_Init(&hcrc) != HAL_OK)
        Error_Handler();
}

static void SystemClock_Config(void)
{
    /* CubeMX generates this — configure for 64 MHz HSI PLL on G071 */
}

/* ------------------------------------------------------------------ */
/*  Main                                                               */
/* ------------------------------------------------------------------ */

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_USART2_UART_Init();
    MX_IWDG_Init();
    MX_CRC_Init();

    /* ---- Pre-RTOS global init ---- */
    blackbox_init(&g_blackbox);

    /* ---- Create FreeRTOS IPC objects ---- */
    g_sensor_queue = osMessageQueueNew(4, sizeof(sensor_data_t), NULL);
    g_state_mutex  = osMutexNew(NULL);
    g_fault_flags  = osEventFlagsNew(NULL);

    /* ---- Create tasks ---- */
    h_sensor_task    = osThreadNew(task_sensor,    NULL, &sensor_attr);
    h_fsm_task       = osThreadNew(task_fsm,       NULL, &fsm_attr);
    h_telemetry_task = osThreadNew(task_telemetry, NULL, &telemetry_attr);
    h_health_task    = osThreadNew(task_health,    NULL, &health_attr);

    /* ---- Register task handles with health monitor ---- */
    task_registry_t reg = {
        .sensor_task    = h_sensor_task,
        .fsm_task       = h_fsm_task,
        .telemetry_task = h_telemetry_task,
        .health_task    = h_health_task,
    };
    health_init(&reg);

    /* ---- Start FreeRTOS scheduler — does not return ---- */
    osKernelStart();

    /* Should never reach here */
    for (;;) {}
}

/* ------------------------------------------------------------------ */
/*  Error handler                                                       */
/* ------------------------------------------------------------------ */

void Error_Handler(void)
{
    __disable_irq();
    /* Spin — debugger will catch this or IWDG will reset */
    for (;;) {}
}

/* FreeRTOS stack overflow hook */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    Error_Handler();
}

/* FreeRTOS malloc failed hook */
void vApplicationMallocFailedHook(void)
{
    Error_Handler();
}
